version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'

  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 3005:8080

  app:
    image: node:16.18.0
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: npm run dev
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/usr/app
    working_dir: /usr/app
